llm:
  provider: OPENAI

  meta:
    model: gpt-4o-mini
    max_tokens: 15000
    temperature: 0.3

  http_client:
    timeout: 120
    api_url: https://api.openai.com/v1

vcs:
  provider: GITHUB

  http_client:
    timeout: 120
    api_url: https://api.github.com

prompt:
  include_agent_prompts: false
  include_inline_prompts: false
  include_context_prompts: false
  include_summary_prompts: false
  include_inline_reply_prompts: false
  include_summary_reply_prompts: false
  inline_prompt_files: [ ./docs/prompts/python/inline/strict.md ]
  context_prompt_files: [ ./docs/prompts/python/inline/strict.md ]
  summary_prompt_files: [ ./docs/prompts/python/summary/strict.md ]
  inline_reply_prompt_files: [ ./docs/prompts/python/inline_reply/strict.md ]
  summary_reply_prompt_files: [ ./docs/prompts/python/summary_reply/strict.md ]

artifacts:
  llm_dir: ./artifacts/llm
  vcs_dir: ./artifacts/vcs
  llm_enabled: true
  vcs_enabled: true